// data.js
// the data objects are all defined here

// pokemon missing from pokepast.es
window.replacements = new Set([
    "poltchageist",
    "sinistcha",
    "sinistcha-masterpiece",
    "ursaluna-bloodmoon",
    "okidogi",
    "munkidori",
    "fezandipiti",
    "ogerpon",
    //"ogerpon-cornerstone",
    //"ogerpon-hearthflame",
    //"ogerpon-wellspring",
    "growlithe-hisui",
    "arcanine-hisui",
    "voltorb-hisui",
    "electrode-hisui",
    "typhlosion-hisui",
    "qwilfish-hisui",
    "overqwil",
    "sneasel-hisui",
    "samurott-hisui",
    "lilligant-hisui",
    "zorua-hisui",
    "zoroark-hisui",
    "braviary-hisui",
    "sliggoo-hisui",
    "goodra-hisui",
    "avalugg-hisui",
    "decidueye-hisui",
    "archaludon",
    "hydrapple",
    "iron boulder",
    "iron crown",
    "raging bolt",
    "gouging fire",
    "terapagos",
    "terapagos-terastal",
    "terapagos-stellar",
    "walking wake",
    "iron leaves",
    "sirfetch’d",
    "zygarde-10%",
    "zygarde-complete",
    "greninja-ash",
    "greninja-bond",
    "pecharunt",
    "arceus-bug",
    "arceus-dark",
    "arceus-dragon",
    "arceus-electric",
    "arceus-fairy",
    "arceus-fighting",
    "arceus-fire",
    "arceus-flying",
    "arceus-ghost",
    "arceus-grass",
    "arceus-ground",
    "arceus-ice",
    "arceus-poison",
    "arceus-psychic",
    "arceus-rock",
    "arceus-steel",
    "arceus-water",
    "dialga-origin",
    "palkia-origin",
    "magearna-original",
    "magearna-mega",
    "magearna-original-mega",
    "greninja-battle-bond",
    "ogerpon-cornerstone-mask",
    "ogerpon-hearthflame-mask",
    "ogerpon-wellspring-mask",
    // Pokemon ZA/Champions additions
    "raichu-mega-x",
    "raichu-mega-y",    
    "clefable-mega",    
    "victreebel-mega",  
    "starmie-mega",     
    "dragonite-mega",   
    "meganium-mega",    
    "feraligatr-mega",  
    "skarmory-mega",    
    "chimecho-mega",    
    "absol-mega-z",     
    "staraptor-mega",   
    "garchomp-mega-z",  
    "lucario-mega-z",   
    "froslass-mega",    
    "heatran-mega",     
    "darkrai-mega",     
    "emboar-mega",      
    "excadrill-mega",   
    "scolipede-mega",   
    "scrafty-mega",     
    "eelektross-mega",  
    "chandelure-mega",  
    "golurk-mega",      
    "chesnaught-mega",  
    "delphox-mega",     
    "greninja-mega",    
    "pyroar-mega",      
    "floette-mega",
    "floette-eternal",
    "meowstic-mega",    
    //"meowstic-m-mega",    
    //"meowstic-f-mega",    
    "malamar-mega",     
    "barbaracle-mega",  
    "dragalge-mega",    
    "hawlucha-mega",    
    "zygarde-mega",     
    "crabominable-mega",
    "golisopod-mega",   
    "drampa-mega",      
    "zeraora-mega",             
    "falinks-mega",             
    "scovillain-mega",          
    "glimmora-mega",            
    "tatsugiri-curly-mega",           
    "tatsugiri-droopy-mega",    
    "tatsugiri-stretchy-mega",  
    "baxcalibur-mega",
    "great-tusk",   
    "scream-tail",  
    "brute-bonnet", 
    "flutter-mane", 
    "slither-wing",
    "sandy-shocks", 
    "iron-treads",
    "iron-bundle",  
    "iron-hands",
    "iron-jugulis", 
    "iron-moth",
    "iron-thorns",
    "raging-bolt",
    "gouging-fire",
    "walking-wake",
    "iron-leaves",
    "iron-boulder",
    "iron-crown",
]);

// incorrectly spelled cases point to the correct spelling
window.badnames = {
    "walking wake":             "walking-wake",
    "gouging fire":             "gouging-fire",
    "raging bolt":              "raging-bolt",
    "iron leaves":              "iron-leaves",
    "iron boulder":             "iron-boulder",
    "iron crown":               "iron-crown",
    "greninja-bond":            "greninja-battle-bond",
    "sinistcha-masterpiece":    "sinistcha",
    "cornerstone mask ogerpon": "ogerpon-cornerstone-mask",
    "hearthflame mask ogerpon": "ogerpon-hearthflame-mask",
    "wellspring mask ogerpon":  "ogerpon-wellspring-mask",
    "origin forme dialga":      "dialga-origin",
    "origin forme palkia":      "palkia-origin",
    "ogerpon-cornerstone":      "ogerpon-cornerstone-mask",
    "ogerpon-wellspring":       "ogerpon-wellspring-mask",
    "ogerpon-hearthflame":      "ogerpon-hearthflame-mask",
    "meowstic-m-mega":          "meowstic-mega",
    "meowstic-f-mega":          "meowstic-mega",
    "mega floette":             "floette-mega"
};

// for art we need to use chiy.uk for because it is missing from PokeAPI
window.missingPokeApi = [
    "arceus-bug",
    "arceus-dark",
    "arceus-dragon",
    "arceus-electric",
    "arceus-fairy",
    "arceus-fighting",
    "arceus-fire",
    "arceus-flying",
    "arceus-ghost",
    "arceus-grass",
    "arceus-ground",
    "arceus-ice",
    "arceus-poison",
    "arceus-psychic",
    "arceus-rock",
    "arceus-steel",
    "arceus-water"
];

window.items = {
    "cornerstone mask": "https://www.serebii.net/itemdex/sprites/sv/cornerstonemask.png",
    "hearthflame mask": "https://www.serebii.net/itemdex/sprites/sv/hearthflamemask.png",
    "wellspring mask": "https://www.serebii.net/itemdex/sprites/sv/wellspringmask.png",
    "fairy feather": "https://www.serebii.net/itemdex/sprites/sv/fairyfeather.png",
    "lustrous globe": "https://www.serebii.net/itemdex/sprites/sv/lustrousglobe.png",
    "adamant crystal": "https://www.serebii.net/itemdex/sprites/sv/adamantcrystal.png",
    "griseous core": "https://www.serebii.net/itemdex/sprites/sv/griseouscore.png",
    // new mega stones
    "raichunite x": "https://archives.bulbagarden.net/media/upload/d/d8/Bag_Raichunite_X_ZA_Sprite.png",
    "raichunite y": "https://archives.bulbagarden.net/media/upload/c/c0/Bag_Raichunite_Y_ZA_Sprite.png",
    "clefablite": "https://archives.bulbagarden.net/media/upload/4/49/Bag_Clefablite_ZA_Sprite.png",
    "victreebelite": "https://archives.bulbagarden.net/media/upload/3/32/Bag_Victreebelite_ZA_Sprite.png",
    "starminite": "https://archives.bulbagarden.net/media/upload/4/49/Bag_Starminite_ZA_Sprite.png",
    "dragoninite": "https://archives.bulbagarden.net/media/upload/6/69/Bag_Dragoninite_ZA_Sprite.png",
    "meganiumite": "https://archives.bulbagarden.net/media/upload/6/66/Bag_Meganiumite_ZA_Sprite.png",
    "feraligite": "https://archives.bulbagarden.net/media/upload/c/c6/Bag_Feraligite_ZA_Sprite.png",
    "skarmorite": "https://archives.bulbagarden.net/media/upload/e/e5/Bag_Skarmorite_ZA_Sprite.png",
    "chimechite": "https://archives.bulbagarden.net/media/upload/1/1e/Bag_Chimechite_ZA_Sprite.png",
    "absolite z": "https://archives.bulbagarden.net/media/upload/1/18/Bag_Absolite_Z_ZA_Sprite.png",
    "staraptite": "https://archives.bulbagarden.net/media/upload/3/34/Bag_Staraptite_ZA_Sprite.png",
    "garchompite z": "https://archives.bulbagarden.net/media/upload/7/7e/Bag_Garchompite_Z_ZA_Sprite.png",
    "lucarionite z": "https://archives.bulbagarden.net/media/upload/e/e3/Bag_Lucarionite_Z_ZA_Sprite.png",
    "froslassite": "https://archives.bulbagarden.net/media/upload/7/7e/Bag_Froslassite_ZA_Sprite.png",
    "heatranite": "https://archives.bulbagarden.net/media/upload/1/16/Bag_Heatranite_ZA_Sprite.png",
    "darkranite": "https://archives.bulbagarden.net/media/upload/b/bf/Bag_Darkranite_ZA_Sprite.png",
    "emboarite": "https://archives.bulbagarden.net/media/upload/3/36/Bag_Emboarite_ZA_Sprite.png",
    "excadrite": "https://archives.bulbagarden.net/media/upload/8/83/Bag_Excadrite_ZA_Sprite.png",
    "scolipite": "https://archives.bulbagarden.net/media/upload/e/e0/Bag_Scolipite_ZA_Sprite.png",
    "scraftinite": "https://archives.bulbagarden.net/media/upload/5/53/Bag_Scraftinite_ZA_Sprite.png",
    "eelektrossite": "https://archives.bulbagarden.net/media/upload/b/ba/Bag_Eelektrossite_ZA_Sprite.png",
    "chandelurite": "https://archives.bulbagarden.net/media/upload/6/6b/Bag_Chandelurite_ZA_Sprite.png",
    "golurkite": "https://archives.bulbagarden.net/media/upload/5/57/Bag_Golurkite_ZA_Sprite.png",
    "delphoxite": "https://archives.bulbagarden.net/media/upload/9/98/Bag_Delphoxite_ZA_Sprite.png",
    "chesnaughtite": "https://archives.bulbagarden.net/media/upload/c/cf/Bag_Chesnaughtite_ZA_Sprite.png",
    "greninjite": "https://archives.bulbagarden.net/media/upload/4/44/Bag_Greninjite_ZA_Sprite.png",
    "pyroarite": "https://archives.bulbagarden.net/media/upload/9/90/Bag_Pyroarite_ZA_Sprite.png",
    "floettite": "https://archives.bulbagarden.net/media/upload/2/26/Bag_Floettite_ZA_Sprite.png",
    "meowsticite": "https://archives.bulbagarden.net/media/upload/1/11/Bag_Meowsticite_ZA_Sprite.png",
    "malamarite": "https://archives.bulbagarden.net/media/upload/8/81/Bag_Malamarite_ZA_Sprite.png",
    "barbaracite": "https://archives.bulbagarden.net/media/upload/c/c1/Bag_Barbaracite_ZA_Sprite.png",
    "dragalgite": "https://archives.bulbagarden.net/media/upload/a/a6/Bag_Dragalgite_ZA_Sprite.png",
    "hawluchanite": "https://archives.bulbagarden.net/media/upload/6/61/Bag_Hawluchanite_ZA_Sprite.png",
    "zygardite": "https://archives.bulbagarden.net/media/upload/9/91/Bag_Zygardite_ZA_Sprite.png",
    "crabominite": "https://archives.bulbagarden.net/media/upload/8/8a/Bag_Crabominite_ZA_Sprite.png",
    "golisopite": "https://archives.bulbagarden.net/media/upload/4/4c/Bag_Golisopite_ZA_Sprite.png",
    "drampanite": "https://archives.bulbagarden.net/media/upload/1/1e/Bag_Drampanite_ZA_Sprite.png",
    "magearnite": "https://archives.bulbagarden.net/media/upload/3/34/Bag_Magearnite_ZA_Sprite.png",
    "zeraorite": "https://archives.bulbagarden.net/media/upload/5/5e/Bag_Zeraorite_ZA_Sprite.png",
    "falinksite": "https://archives.bulbagarden.net/media/upload/c/c6/Bag_Falinksite_ZA_Sprite.png",
    "scovillainite": "https://archives.bulbagarden.net/media/upload/e/e8/Bag_Scovillainite_ZA_Sprite.png",
    "glimmoranite": "https://archives.bulbagarden.net/media/upload/e/e1/Bag_Glimmoranite_ZA_Sprite.png",
    "tatsugirinite": "https://archives.bulbagarden.net/media/upload/9/99/Bag_Tatsugirinite_ZA_Sprite.png",
    "baxcalibrite": "https://archives.bulbagarden.net/media/upload/a/af/Bag_Baxcalibrite_ZA_Sprite.png",
};

// simple lookup table to match what is found in sprites.version{}
// transparent: prefer front_transparent / front_shiny_transparent (gens 1-2 bake a white bg into front_default)
// noShiny: generation predates shinies — ignore shiny request rather than serving a non-gen sprite
window.GEN_LOOKUP = {
    1: { 
        gen: "generation-i",
        game: "yellow",
        // red-blue
        transparent: true, 
        noShiny: true 
    },
    2: { 
        gen: "generation-ii",
        game: "crystal",
        // gold
        // silver
        transparent: true 
    },
    3: { 
        gen: "generation-iii",
        game: "emerald"
        // ruby-sapphire
        // firered-leafgreen
    },
    4: { 
        gen: "generation-iv",
        game: "platinum"
        //diamond-pearl
        //heartgold-soulsilver
    },
    5: { 
        gen: "generation-v",
        game: "black-white", 
        // 
        animated: true 
    },
    // decided against the non sprite generations
    //6: { gen: "generation-vi",      sub: "x-y" },
    //7: { gen: "generation-vii",     sub: "ultra-sun-ultra-moon" },
    //8: { gen: "generation-viii",    sub: ""
    //9: { gen: "generation-ix",      sub: "scarlet"
};
