// data.js
// the data objects are all defined here

// pokemon missing from pokepast.es
window.replacements = new Set([
    "poltchageist",
    "sinistcha",
    "sinistcha-masterpiece",
    "ursaluna-bloodmoon",
    "okidogi",
    "munkidori",
    "fezandipiti",
    "ogerpon",
    //"ogerpon-cornerstone",
    //"ogerpon-hearthflame",
    //"ogerpon-wellspring",
    "growlithe-hisui",
    "arcanine-hisui",
    "voltorb-hisui",
    "electrode-hisui",
    "typhlosion-hisui",
    "qwilfish-hisui",
    "overqwil",
    "sneasel-hisui",
    "samurott-hisui",
    "lilligant-hisui",
    "zorua-hisui",
    "zoroark-hisui",
    "braviary-hisui",
    "sliggoo-hisui",
    "goodra-hisui",
    "avalugg-hisui",
    "decidueye-hisui",
    "archaludon",
    "hydrapple",
    "iron boulder",
    "iron crown",
    "raging bolt",
    "gouging fire",
    "terapagos",
    "terapagos-terastal",
    "terapagos-stellar",
    "walking wake",
    "iron leaves",
    "sirfetch’d",
    "zygarde-10%",
    "zygarde-complete",
    "greninja-ash",
    "greninja-bond",
    "pecharunt",
    "arceus-bug",
    "arceus-dark",
    "arceus-dragon",
    "arceus-electric",
    "arceus-fairy",
    "arceus-fighting",
    "arceus-fire",
    "arceus-flying",
    "arceus-ghost",
    "arceus-grass",
    "arceus-ground",
    "arceus-ice",
    "arceus-poison",
    "arceus-psychic",
    "arceus-rock",
    "arceus-steel",
    "arceus-water",
    "dialga-origin",
    "palkia-origin",
    "magearna-original",
    "magearna-mega",
    "magearna-original-mega",
    "greninja-battle-bond",
    "ogerpon-cornerstone-mask",
    "ogerpon-hearthflame-mask",
    "ogerpon-wellspring-mask",
    // Pokemon ZA/Champions additions
    "raichu-mega-x",
    "raichu-mega-y",    
    "clefable-mega",    
    "victreebel-mega",  
    "starmie-mega",     
    "dragonite-mega",   
    "meganium-mega",    
    "feraligatr-mega",  
    "skarmory-mega",    
    "chimecho-mega",    
    "absol-mega-z",     
    "staraptor-mega",   
    "garchomp-mega-z",  
    "lucario-mega-z",   
    "froslass-mega",    
    "heatran-mega",     
    "darkrai-mega",     
    "emboar-mega",      
    "excadrill-mega",   
    "scolipede-mega",   
    "scrafty-mega",     
    "eelektross-mega",  
    "chandelure-mega",  
    "golurk-mega",      
    "chesnaught-mega",  
    "delphox-mega",     
    "greninja-mega",    
    "pyroar-mega",      
    "floette-mega",
    "floette-eternal",
    "meowstic-mega",    
    //"meowstic-m-mega",    
    //"meowstic-f-mega",    
    "malamar-mega",     
    "barbaracle-mega",  
    "dragalge-mega",    
    "hawlucha-mega",    
    "zygarde-mega",     
    "crabominable-mega",
    "golisopod-mega",   
    "drampa-mega",      
    "zeraora-mega",             
    "falinks-mega",             
    "scovillain-mega",          
    "glimmora-mega",            
    "tatsugiri-curly-mega",           
    "tatsugiri-droopy-mega",    
    "tatsugiri-stretchy-mega",  
    "baxcalibur-mega",
    "great-tusk",   
    "scream-tail",  
    "brute-bonnet", 
    "flutter-mane", 
    "slither-wing",
    "sandy-shocks", 
    "iron-treads",
    "iron-bundle",  
    "iron-hands",
    "iron-jugulis", 
    "iron-moth",
    "iron-thorns",
    "raging-bolt",
    "gouging-fire",
    "walking-wake",
    "iron-leaves",
    "iron-boulder",
    "iron-crown",
]);

// incorrectly spelled cases point to the correct spelling
window.badnames = {
    "walking wake":             "walking-wake",
    "gouging fire":             "gouging-fire",
    "raging bolt":              "raging-bolt",
    "iron leaves":              "iron-leaves",
    "iron boulder":             "iron-boulder",
    "iron crown":               "iron-crown",
    "greninja-bond":            "greninja-battle-bond",
    "sinistcha-masterpiece":    "sinistcha",
    "cornerstone mask ogerpon": "ogerpon-cornerstone-mask",
    "hearthflame mask ogerpon": "ogerpon-hearthflame-mask",
    "wellspring mask ogerpon":  "ogerpon-wellspring-mask",
    "origin forme dialga":      "dialga-origin",
    "origin forme palkia":      "palkia-origin",
    "ogerpon-cornerstone":      "ogerpon-cornerstone-mask",
    "ogerpon-wellspring":       "ogerpon-wellspring-mask",
    "ogerpon-hearthflame":      "ogerpon-hearthflame-mask",
    "meowstic-m-mega":          "meowstic-mega",
    "meowstic-f-mega":          "meowstic-mega",
    "mega floette":             "floette-mega",
    "indeedee ♂":               "indeedee-male",
    "indeedee ♀":               "indeedee-female",
    "indeedee-m":               "indeedee-male",
    "indeedee-f":               "indeedee-female"    
};

// for art we need to use chiy.uk for because it is missing from PokeAPI
window.missingPokeApi = [
    "arceus-bug",
    "arceus-dark",
    "arceus-dragon",
    "arceus-electric",
    "arceus-fairy",
    "arceus-fighting",
    "arceus-fire",
    "arceus-flying",
    "arceus-ghost",
    "arceus-grass",
    "arceus-ground",
    "arceus-ice",
    "arceus-poison",
    "arceus-psychic",
    "arceus-rock",
    "arceus-steel",
    "arceus-water"
];

window.items = {
    "cornerstone mask": "https://www.serebii.net/itemdex/sprites/sv/cornerstonemask.png",
    "hearthflame mask": "https://www.serebii.net/itemdex/sprites/sv/hearthflamemask.png",
    "wellspring mask": "https://www.serebii.net/itemdex/sprites/sv/wellspringmask.png",
    "fairy feather": "https://www.serebii.net/itemdex/sprites/sv/fairyfeather.png",
    "lustrous globe": "https://www.serebii.net/itemdex/sprites/sv/lustrousglobe.png",
    "adamant crystal": "https://www.serebii.net/itemdex/sprites/sv/adamantcrystal.png",
    "griseous core": "https://www.serebii.net/itemdex/sprites/sv/griseouscore.png",
    // new mega stones
    // Pokemon Champions bag sprites
    "raichunite x":   "https://archives.bulbagarden.net/media/upload/3/3a/Bag_Raichunite_X_CP_Sprite.png",
    "raichunite y":   "https://archives.bulbagarden.net/media/upload/6/65/Bag_Raichunite_Y_CP_Sprite.png",
    "clefablite":     "https://archives.bulbagarden.net/media/upload/d/d7/Bag_Clefablite_CP_Sprite.png",
    "victreebelite":  "https://archives.bulbagarden.net/media/upload/6/65/Bag_Victreebelite_CP_Sprite.png",
    "starminite":     "https://archives.bulbagarden.net/media/upload/c/c2/Bag_Starminite_CP_Sprite.png",
    "dragoninite":    "https://archives.bulbagarden.net/media/upload/4/41/Bag_Dragoninite_CP_Sprite.png",
    "meganiumite":    "https://archives.bulbagarden.net/media/upload/c/c5/Bag_Meganiumite_CP_Sprite.png",
    "feraligite":     "https://archives.bulbagarden.net/media/upload/7/7c/Bag_Feraligite_CP_Sprite.png",
    "skarmorite":     "https://archives.bulbagarden.net/media/upload/e/e8/Bag_Skarmorite_CP_Sprite.png",
    "chimechite":     "https://archives.bulbagarden.net/media/upload/0/0d/Bag_Chimechite_CP_Sprite.png",
    "absolite z":     "https://archives.bulbagarden.net/media/upload/9/95/Bag_Absolite_Z_CP_Sprite.png",
    "staraptite":     "https://archives.bulbagarden.net/media/upload/1/1c/Bag_Staraptite_CP_Sprite.png",
    "garchompite z":  "https://archives.bulbagarden.net/media/upload/4/4b/Bag_Garchompite_Z_CP_Sprite.png",
    "lucarionite z":  "https://archives.bulbagarden.net/media/upload/e/ea/Bag_Lucarionite_Z_CP_Sprite.png",
    "froslassite":    "https://archives.bulbagarden.net/media/upload/7/70/Bag_Froslassite_CP_Sprite.png",
    "emboarite":      "https://archives.bulbagarden.net/media/upload/3/3b/Bag_Emboarite_CP_Sprite.png",
    "excadrite":      "https://archives.bulbagarden.net/media/upload/9/9c/Bag_Excadrite_CP_Sprite.png",
    "scolipite":      "https://archives.bulbagarden.net/media/upload/2/2d/Bag_Scolipite_CP_Sprite.png",
    "scraftinite":    "https://archives.bulbagarden.net/media/upload/f/ff/Bag_Scraftinite_CP_Sprite.png",
    "eelektrossite":  "https://archives.bulbagarden.net/media/upload/3/3d/Bag_Eelektrossite_CP_Sprite.png",
    "chandelurite":   "https://archives.bulbagarden.net/media/upload/e/e2/Bag_Chandelurite_CP_Sprite.png",
    "golurkite":      "https://archives.bulbagarden.net/media/upload/b/bf/Bag_Golurkite_CP_Sprite.png",
    "delphoxite":     "https://archives.bulbagarden.net/media/upload/0/0f/Bag_Delphoxite_CP_Sprite.png",
    "chesnaughtite":  "https://archives.bulbagarden.net/media/upload/5/50/Bag_Chesnaughtite_CP_Sprite.png",
    "greninjite":     "https://archives.bulbagarden.net/media/upload/b/b6/Bag_Greninjite_CP_Sprite.png",
    "pyroarite":      "https://archives.bulbagarden.net/media/upload/5/59/Bag_Pyroarite_CP_Sprite.png",
    "floettite":      "https://archives.bulbagarden.net/media/upload/0/02/Bag_Floettite_CP_Sprite.png",
    "meowsticite":    "https://archives.bulbagarden.net/media/upload/2/2a/Bag_Meowsticite_CP_Sprite.png",
    "malamarite":     "https://archives.bulbagarden.net/media/upload/9/99/Bag_Malamarite_CP_Sprite.png",
    "barbaracite":    "https://archives.bulbagarden.net/media/upload/e/e6/Bag_Barbaracite_CP_Sprite.png",
    "dragalgite":     "https://archives.bulbagarden.net/media/upload/4/4b/Bag_Dragalgite_CP_Sprite.png",
    "hawluchanite":   "https://archives.bulbagarden.net/media/upload/4/4b/Bag_Hawluchanite_CP_Sprite.png",
    "crabominite":    "https://archives.bulbagarden.net/media/upload/8/83/Bag_Crabominite_CP_Sprite.png",
    "golisopite":     "https://archives.bulbagarden.net/media/upload/2/2b/Bag_Golisopite_CP_Sprite.png",
    "drampanite":     "https://archives.bulbagarden.net/media/upload/d/d5/Bag_Drampanite_CP_Sprite.png",
    "falinksite":     "https://archives.bulbagarden.net/media/upload/2/22/Bag_Falinksite_CP_Sprite.png",
    "scovillainite":  "https://archives.bulbagarden.net/media/upload/b/bc/Bag_Scovillainite_CP_Sprite.png",
    "glimmoranite":   "https://archives.bulbagarden.net/media/upload/f/f3/Bag_Glimmoranite_CP_Sprite.png",
    "baxcalibrite":   "https://archives.bulbagarden.net/media/upload/e/e6/Bag_Baxcalibrite_CP_Sprite.png",
    // ZA sprite cause not in champs yet
    "heatranite":     "https://archives.bulbagarden.net/media/upload/1/16/Bag_Heatranite_ZA_Sprite.png",
    "darkranite":     "https://archives.bulbagarden.net/media/upload/b/bf/Bag_Darkranite_ZA_Sprite.png",
    "zygardite":      "https://archives.bulbagarden.net/media/upload/9/91/Bag_Zygardite_ZA_Sprite.png",
    "magearnite":     "https://archives.bulbagarden.net/media/upload/3/34/Bag_Magearnite_ZA_Sprite.png",
    "zeraorite":      "https://archives.bulbagarden.net/media/upload/5/5e/Bag_Zeraorite_ZA_Sprite.png",
    "tatsugirinite":  "https://archives.bulbagarden.net/media/upload/9/99/Bag_Tatsugirinite_ZA_Sprite.png",
};

// simple lookup table to match what is found in sprites.version{}
// transparent: prefer front_transparent / front_shiny_transparent (gens 1-2 bake a white bg into front_default)
// noShiny: generation predates shinies — ignore shiny request rather than serving a non-gen sprite
window.GEN_LOOKUP = {
    1: { 
        gen: "generation-i",
        game: "yellow",
        // red-blue
        transparent: true, 
        noShiny: true 
    },
    2: { 
        gen: "generation-ii",
        game: "crystal",
        // gold
        // silver
        transparent: true 
    },
    3: { 
        gen: "generation-iii",
        game: "emerald"
        // ruby-sapphire
        // firered-leafgreen
    },
    4: { 
        gen: "generation-iv",
        game: "platinum"
        //diamond-pearl
        //heartgold-soulsilver
    },
    5: { 
        gen: "generation-v",
        game: "black-white", 
        // 
        animated: true 
    },
    // decided against the non sprite generations
    //6: { gen: "generation-vi",      sub: "x-y" },
    //7: { gen: "generation-vii",     sub: "ultra-sun-ultra-moon" },
    //8: { gen: "generation-viii",    sub: ""
    //9: { gen: "generation-ix",      sub: "scarlet"
};

