// data.js
// the data objects are all defined here

// pokemon missing from pokepast.es
window.replacements = new Set([
    "poltchageist",
    "sinistcha",
    "sinistcha-masterpiece",
    "ursaluna-bloodmoon",
    "okidogi",
    "munkidori",
    "fezandipiti",
    "ogerpon",
    //"ogerpon-cornerstone",
    //"ogerpon-hearthflame",
    //"ogerpon-wellspring",
    "growlithe-hisui",
    "arcanine-hisui",
    "voltorb-hisui",
    "electrode-hisui",
    "typhlosion-hisui",
    "qwilfish-hisui",
    "overqwil",
    "sneasel-hisui",
    "samurott-hisui",
    "lilligant-hisui",
    "zorua-hisui",
    "zoroark-hisui",
    "braviary-hisui",
    "sliggoo-hisui",
    "goodra-hisui",
    "avalugg-hisui",
    "decidueye-hisui",
    "archaludon",
    "hydrapple",
    "iron boulder",
    "iron crown",
    "raging bolt",
    "gouging fire",
    "terapagos",
    "terapagos-terastal",
    "terapagos-stellar",
    "walking wake",
    "iron leaves",
    "sirfetch’d",
    "zygarde-10%",
    "zygarde-complete",
    "greninja-ash",
    "greninja-bond",
    "pecharunt",
    "arceus-bug",
    "arceus-dark",
    "arceus-dragon",
    "arceus-electric",
    "arceus-fairy",
    "arceus-fighting",
    "arceus-fire",
    "arceus-flying",
    "arceus-ghost",
    "arceus-grass",
    "arceus-ground",
    "arceus-ice",
    "arceus-poison",
    "arceus-psychic",
    "arceus-rock",
    "arceus-steel",
    "arceus-water",
    "dialga-origin",
    "palkia-origin",
    "magearna-original",
    "magearna-mega",
    "magearna-original-mega",
    "greninja-battle-bond",
    "ogerpon-cornerstone-mask",
    "ogerpon-hearthflame-mask",
    "ogerpon-wellspring-mask",
    // Pokemon ZA/Champions additions
    "raichu-mega-x",
    "raichu-mega-y",    
    "clefable-mega",    
    "victreebel-mega",  
    "starmie-mega",     
    "dragonite-mega",   
    "meganium-mega",    
    "feraligatr-mega",  
    "skarmory-mega",    
    "chimecho-mega",    
    "absol-mega-z",     
    "staraptor-mega",   
    "garchomp-mega-z",  
    "lucario-mega-z",   
    "froslass-mega",    
    "heatran-mega",     
    "darkrai-mega",     
    "emboar-mega",      
    "excadrill-mega",   
    "scolipede-mega",   
    "scrafty-mega",     
    "eelektross-mega",  
    "chandelure-mega",  
    "golurk-mega",      
    "chesnaught-mega",  
    "delphox-mega",     
    "greninja-mega",    
    "pyroar-mega",      
    "floette-mega",
    "floette-eternal",
    "meowstic-mega",    
    //"meowstic-m-mega",    
    //"meowstic-f-mega",    
    "malamar-mega",     
    "barbaracle-mega",  
    "dragalge-mega",    
    "hawlucha-mega",    
    "zygarde-mega",     
    "crabominable-mega",
    "golisopod-mega",   
    "drampa-mega",      
    "zeraora-mega",             
    "falinks-mega",             
    "scovillain-mega",          
    "glimmora-mega",            
    "tatsugiri-curly-mega",           
    "tatsugiri-droopy-mega",    
    "tatsugiri-stretchy-mega",  
    "baxcalibur-mega",
    "great-tusk",   
    "scream-tail",  
    "brute-bonnet", 
    "flutter-mane", 
    "slither-wing",
    "sandy-shocks", 
    "iron-treads",
    "iron-bundle",  
    "iron-hands",
    "iron-jugulis", 
    "iron-moth",
    "iron-thorns",
    "raging-bolt",
    "gouging-fire",
    "walking-wake",
    "iron-leaves",
    "iron-boulder",
    "iron-crown",
]);

// incorrectly spelled cases point to the correct spelling
window.badnames = {
    "walking wake":             "walking-wake",
    "gouging fire":             "gouging-fire",
    "raging bolt":              "raging-bolt",
    "iron leaves":              "iron-leaves",
    "iron boulder":             "iron-boulder",
    "iron crown":               "iron-crown",
    "greninja-bond":            "greninja-battle-bond",
    "sinistcha-masterpiece":    "sinistcha",
    "cornerstone mask ogerpon": "ogerpon-cornerstone-mask",
    "hearthflame mask ogerpon": "ogerpon-hearthflame-mask",
    "wellspring mask ogerpon":  "ogerpon-wellspring-mask",
    "origin forme dialga":      "dialga-origin",
    "origin forme palkia":      "palkia-origin",
    "ogerpon-cornerstone":      "ogerpon-cornerstone-mask",
    "ogerpon-wellspring":       "ogerpon-wellspring-mask",
    "ogerpon-hearthflame":      "ogerpon-hearthflame-mask",
    "meowstic-m-mega":          "meowstic-mega",
    "meowstic-f-mega":          "meowstic-mega",
    "mega floette":             "floette-mega"
};

// for art we need to use chiy.uk for because it is missing from PokeAPI
window.missingPokeApi = [
    "arceus-bug",
    "arceus-dark",
    "arceus-dragon",
    "arceus-electric",
    "arceus-fairy",
    "arceus-fighting",
    "arceus-fire",
    "arceus-flying",
    "arceus-ghost",
    "arceus-grass",
    "arceus-ground",
    "arceus-ice",
    "arceus-poison",
    "arceus-psychic",
    "arceus-rock",
    "arceus-steel",
    "arceus-water"
];

window.items = {
    "cornerstone mask": "https://www.serebii.net/itemdex/sprites/sv/cornerstonemask.png",
    "hearthflame mask": "https://www.serebii.net/itemdex/sprites/sv/hearthflamemask.png",
    "wellspring mask": "https://www.serebii.net/itemdex/sprites/sv/wellspringmask.png",
    "fairy feather": "https://www.serebii.net/itemdex/sprites/sv/fairyfeather.png",
    "lustrous globe": "https://www.serebii.net/itemdex/sprites/sv/lustrousglobe.png",
    "adamant crystal": "https://www.serebii.net/itemdex/sprites/sv/adamantcrystal.png",
    "griseous core": "https://www.serebii.net/itemdex/sprites/sv/griseouscore.png",
    // new mega stones
    "raichunite x": "https://www.serebii.net/pokedex-sv/evoicon/mega26x.png",
    "raichunite y": "https://www.serebii.net/pokedex-sv/evoicon/mega26y.png",
    "clefablite": "https://www.serebii.net/pokedex-sv/evoicon/mega36.png",
    "victreebelite": "https://www.serebii.net/pokedex-sv/evoicon/mega71.png",
    "starminite": "https://www.serebii.net/pokedex-sv/evoicon/mega121.png",
    "dragoninite": "https://www.serebii.net/pokedex-sv/evoicon/mega149.png",
    "meganiumite": "https://www.serebii.net/pokedex-sv/evoicon/mega154.png",
    "feraligite": "https://www.serebii.net/pokedex-sv/evoicon/mega160.png",
    "skarmorite": "https://www.serebii.net/pokedex-sv/evoicon/mega227.png",
    "chimechite": "https://www.serebii.net/pokedex-sv/evoicon/mega358.png",
    "absolite z": "https://www.serebii.net/pokedex-sv/evoicon/mega359z.png",
    "staraptite": "https://www.serebii.net/pokedex-sv/evoicon/mega398.png",
    "garchompite z": "https://www.serebii.net/pokedex-sv/evoicon/mega445z.png",
    "lucarionite z": "https://www.serebii.net/pokedex-sv/evoicon/mega448z.png",
    "froslassite": "https://www.serebii.net/pokedex-sv/evoicon/mega478.png",
    "heatranite": "https://www.serebii.net/pokedex-sv/evoicon/mega485.png",
    "darkranite": "https://www.serebii.net/pokedex-sv/evoicon/mega491.png",
    "emboarite": "https://www.serebii.net/pokedex-sv/evoicon/mega500.png",
    "excadrite": "https://www.serebii.net/pokedex-sv/evoicon/mega530.png",
    "scolipite": "https://www.serebii.net/pokedex-sv/evoicon/mega545.png",
    "scraftinite": "https://www.serebii.net/pokedex-sv/evoicon/mega560.png",
    "eelektrossite": "https://www.serebii.net/pokedex-sv/evoicon/mega604.png",
    "chandelurite": "https://www.serebii.net/pokedex-sv/evoicon/mega609.png",
    "golurkite": "https://www.serebii.net/pokedex-sv/evoicon/mega623.png",
    "delphoxite": "https://www.serebii.net/pokedex-sv/evoicon/mega655.png",
    "chesnaughtite": "https://www.serebii.net/pokedex-sv/evoicon/mega652.png",
    "greninjite": "https://www.serebii.net/pokedex-sv/evoicon/mega658.png",
    "pyroarite": "https://www.serebii.net/pokedex-sv/evoicon/mega668.png",
    "floettite": "https://www.serebii.net/pokedex-sv/evoicon/mega670.png",
    "meowsticite": "https://www.serebii.net/pokedex-sv/evoicon/mega678.png",
    "malamarite": "https://www.serebii.net/pokedex-sv/evoicon/mega687.png",
    "barbaracite": "https://www.serebii.net/pokedex-sv/evoicon/mega689.png",
    "dragalgite": "https://www.serebii.net/pokedex-sv/evoicon/mega691.png",
    "hawluchanite": "https://www.serebii.net/pokedex-sv/evoicon/mega701.png",
    "zygardite": "https://www.serebii.net/pokedex-sv/evoicon/mega718.png",
    "crabominite": "https://www.serebii.net/pokedex-sv/evoicon/mega740.png",
    "golisopite": "https://www.serebii.net/pokedex-sv/evoicon/mega768.png",
    "drampanite": "https://www.serebii.net/pokedex-sv/evoicon/mega780.png",
    "magearnite": "https://www.serebii.net/pokedex-sv/evoicon/mega801.png",
    "zeraorite": "https://www.serebii.net/pokedex-sv/evoicon/mega807.png",
    "falinksite": "https://www.serebii.net/pokedex-sv/evoicon/mega870.png",
    "scovillainite": "https://www.serebii.net/pokedex-sv/evoicon/mega952.png",
    "glimmoranite": "https://www.serebii.net/pokedex-sv/evoicon/mega970.png",
    "tatsugirinite": "https://www.serebii.net/pokedex-sv/evoicon/mega978.png",
    "baxcalibrite": "https://www.serebii.net/pokedex-sv/evoicon/mega998.png",
};

// simple lookup table to match what is found in sprites.version{}
// transparent: prefer front_transparent / front_shiny_transparent (gens 1-2 bake a white bg into front_default)
// noShiny: generation predates shinies — ignore shiny request rather than serving a non-gen sprite
window.GEN_LOOKUP = {
    1: { 
        gen: "generation-i",
        game: "yellow",
        // red-blue
        transparent: true, 
        noShiny: true 
    },
    2: { 
        gen: "generation-ii",
        game: "crystal",
        // gold
        // silver
        transparent: true 
    },
    3: { 
        gen: "generation-iii",
        game: "emerald"
        // ruby-sapphire
        // firered-leafgreen
    },
    4: { 
        gen: "generation-iv",
        game: "platinum"
    },
    5: { 
        gen: "generation-v",
        game: "black-white", 
        animated: true 
    },
    // decided against the non sprite generations
    //6: { gen: "generation-vi",      sub: "x-y" },
    //7: { gen: "generation-vii",     sub: "ultra-sun-ultra-moon" },
    //8: { gen: "generation-viii",    sub: ""
    //9: { gen: "generation-ix",      sub: "scarlet"
};
